# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        if not mainwindow.objectName():
            mainwindow.setObjectName(u"mainwindow")
        mainwindow.resize(1100, 600)
        mainwindow.setMinimumSize(QSize(1100, 600))
        mainwindow.setMaximumSize(QSize(1100, 600))
        font = QFont()
        font.setFamilies([u"Unispace"])
        font.setPointSize(16)
        font.setBold(True)
        mainwindow.setFont(font)
        self.centralwidget = QWidget(mainwindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setFont(font)
        self.tabwidget = QTabWidget(self.centralwidget)
        self.tabwidget.setObjectName(u"tabwidget")
        self.tabwidget.setGeometry(QRect(0, 0, 1100, 311))
        self.tabwidget.setMaximumSize(QSize(1100, 600))
        palette = QPalette()
        brush = QBrush(QColor(53, 53, 53, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        brush1 = QBrush(QColor(0, 255, 0, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush2)
        brush3 = QBrush(QColor(52, 52, 52, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush2)
        self.tabwidget.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Unispace"])
        font1.setPointSize(20)
        font1.setBold(True)
        font1.setItalic(False)
        self.tabwidget.setFont(font1)
        self.tab_encrypt = QWidget()
        self.tab_encrypt.setObjectName(u"tab_encrypt")
        self.browsebutton_en = QPushButton(self.tab_encrypt)
        self.browsebutton_en.setObjectName(u"browsebutton_en")
        self.browsebutton_en.setGeometry(QRect(960, 0, 110, 35))
        font2 = QFont()
        font2.setFamilies([u"Unispace"])
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setItalic(False)
        self.browsebutton_en.setFont(font2)
        self.randomkeybutton_en = QPushButton(self.tab_encrypt)
        self.randomkeybutton_en.setObjectName(u"randomkeybutton_en")
        self.randomkeybutton_en.setGeometry(QRect(960, 80, 110, 35))
        self.randomkeybutton_en.setFont(font2)
        self.textfilepath_en = QLabel(self.tab_encrypt)
        self.textfilepath_en.setObjectName(u"textfilepath_en")
        self.textfilepath_en.setGeometry(QRect(0, 0, 110, 35))
        self.textfilepath_en.setFont(font2)
        self.filepathline_en = QLineEdit(self.tab_encrypt)
        self.filepathline_en.setObjectName(u"filepathline_en")
        self.filepathline_en.setGeometry(QRect(110, 0, 850, 35))
        font3 = QFont()
        font3.setFamilies([u"Unispace"])
        font3.setPointSize(16)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        self.filepathline_en.setFont(font3)
        self.textkeyhex_en = QLabel(self.tab_encrypt)
        self.textkeyhex_en.setObjectName(u"textkeyhex_en")
        self.textkeyhex_en.setGeometry(QRect(0, 80, 110, 35))
        self.textkeyhex_en.setFont(font2)
        self.textpassword_en = QLabel(self.tab_encrypt)
        self.textpassword_en.setObjectName(u"textpassword_en")
        self.textpassword_en.setGeometry(QRect(0, 120, 110, 35))
        self.textpassword_en.setFont(font2)
        self.keyhexline_en = QLineEdit(self.tab_encrypt)
        self.keyhexline_en.setObjectName(u"keyhexline_en")
        self.keyhexline_en.setGeometry(QRect(110, 80, 850, 35))
        self.keyhexline_en.setFont(font3)
        self.passwordline_en = QLineEdit(self.tab_encrypt)
        self.passwordline_en.setObjectName(u"passwordline_en")
        self.passwordline_en.setGeometry(QRect(110, 120, 850, 35))
        self.passwordline_en.setFont(font3)
        self.paste_password_en = QPushButton(self.tab_encrypt)
        self.paste_password_en.setObjectName(u"paste_password_en")
        self.paste_password_en.setGeometry(QRect(960, 120, 110, 35))
        self.paste_password_en.setFont(font2)
        self.encrypt = QPushButton(self.tab_encrypt)
        self.encrypt.setObjectName(u"encrypt")
        self.encrypt.setGeometry(QRect(830, 160, 240, 80))
        font4 = QFont()
        font4.setFamilies([u"Unispace"])
        font4.setPointSize(28)
        font4.setBold(True)
        font4.setItalic(False)
        font4.setStrikeOut(False)
        self.encrypt.setFont(font4)
        self.encrypt.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.textoutput_en = QLabel(self.tab_encrypt)
        self.textoutput_en.setObjectName(u"textoutput_en")
        self.textoutput_en.setGeometry(QRect(0, 40, 110, 35))
        font5 = QFont()
        font5.setFamilies([u"Unispace"])
        font5.setPointSize(16)
        font5.setBold(True)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        font5.setKerning(True)
        self.textoutput_en.setFont(font5)
        self.textoutput_en.setTextFormat(Qt.TextFormat.AutoText)
        self.outputline_en = QLineEdit(self.tab_encrypt)
        self.outputline_en.setObjectName(u"outputline_en")
        self.outputline_en.setGeometry(QRect(110, 40, 850, 35))
        self.outputline_en.setFont(font3)
        self.browsebutton_en_output = QPushButton(self.tab_encrypt)
        self.browsebutton_en_output.setObjectName(u"browsebutton_en_output")
        self.browsebutton_en_output.setGeometry(QRect(960, 40, 110, 35))
        self.browsebutton_en_output.setFont(font2)
        self.tabwidget.addTab(self.tab_encrypt, "")
        self.tab_decrypt = QWidget()
        self.tab_decrypt.setObjectName(u"tab_decrypt")
        self.textpassword_de = QLabel(self.tab_decrypt)
        self.textpassword_de.setObjectName(u"textpassword_de")
        self.textpassword_de.setGeometry(QRect(0, 120, 110, 35))
        self.textpassword_de.setFont(font2)
        self.passwordline_de = QLineEdit(self.tab_decrypt)
        self.passwordline_de.setObjectName(u"passwordline_de")
        self.passwordline_de.setGeometry(QRect(110, 120, 850, 35))
        self.passwordline_de.setFont(font3)
        self.textfilepath_de = QLabel(self.tab_decrypt)
        self.textfilepath_de.setObjectName(u"textfilepath_de")
        self.textfilepath_de.setGeometry(QRect(0, 0, 110, 35))
        self.textfilepath_de.setFont(font2)
        self.textkeyhex_de = QLabel(self.tab_decrypt)
        self.textkeyhex_de.setObjectName(u"textkeyhex_de")
        self.textkeyhex_de.setGeometry(QRect(0, 80, 110, 35))
        self.textkeyhex_de.setFont(font2)
        self.keyhexline_de = QLineEdit(self.tab_decrypt)
        self.keyhexline_de.setObjectName(u"keyhexline_de")
        self.keyhexline_de.setGeometry(QRect(110, 80, 850, 35))
        self.keyhexline_de.setFont(font3)
        self.filepathline_de = QLineEdit(self.tab_decrypt)
        self.filepathline_de.setObjectName(u"filepathline_de")
        self.filepathline_de.setGeometry(QRect(110, 0, 850, 35))
        self.filepathline_de.setFont(font3)
        self.browsebutton_de = QPushButton(self.tab_decrypt)
        self.browsebutton_de.setObjectName(u"browsebutton_de")
        self.browsebutton_de.setGeometry(QRect(960, 0, 110, 35))
        self.browsebutton_de.setFont(font2)
        self.paste_hex_de = QPushButton(self.tab_decrypt)
        self.paste_hex_de.setObjectName(u"paste_hex_de")
        self.paste_hex_de.setGeometry(QRect(960, 80, 110, 35))
        self.paste_hex_de.setFont(font2)
        self.paste_password_de = QPushButton(self.tab_decrypt)
        self.paste_password_de.setObjectName(u"paste_password_de")
        self.paste_password_de.setGeometry(QRect(960, 120, 110, 35))
        self.paste_password_de.setFont(font2)
        self.decrypt = QPushButton(self.tab_decrypt)
        self.decrypt.setObjectName(u"decrypt")
        self.decrypt.setGeometry(QRect(830, 160, 240, 80))
        font6 = QFont()
        font6.setFamilies([u"Unispace"])
        font6.setPointSize(28)
        font6.setBold(True)
        font6.setItalic(False)
        self.decrypt.setFont(font6)
        self.decrypt.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.textoutput_de = QLabel(self.tab_decrypt)
        self.textoutput_de.setObjectName(u"textoutput_de")
        self.textoutput_de.setGeometry(QRect(0, 40, 110, 35))
        self.textoutput_de.setFont(font2)
        self.textoutput_de.setTextFormat(Qt.TextFormat.AutoText)
        self.outputline_de = QLineEdit(self.tab_decrypt)
        self.outputline_de.setObjectName(u"outputline_de")
        self.outputline_de.setGeometry(QRect(110, 40, 850, 35))
        self.outputline_de.setFont(font3)
        self.browsebutton_de_output = QPushButton(self.tab_decrypt)
        self.browsebutton_de_output.setObjectName(u"browsebutton_de_output")
        self.browsebutton_de_output.setGeometry(QRect(960, 40, 110, 35))
        self.browsebutton_de_output.setFont(font2)
        self.tabwidget.addTab(self.tab_decrypt, "")
        self.messagedisplay = QPlainTextEdit(self.centralwidget)
        self.messagedisplay.setObjectName(u"messagedisplay")
        self.messagedisplay.setGeometry(QRect(5, 320, 1090, 275))
        self.messagedisplay.setFont(font)
        self.messagedisplay.setReadOnly(True)
        mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainwindow)

        self.tabwidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainwindow)
    # setupUi

    def retranslateUi(self, mainwindow):
        mainwindow.setWindowTitle(QCoreApplication.translate("mainwindow", u"Encryptor Decryptor", None))
        self.browsebutton_en.setText(QCoreApplication.translate("mainwindow", u"Browse", None))
        self.randomkeybutton_en.setText(QCoreApplication.translate("mainwindow", u"Random", None))
        self.textfilepath_en.setText(QCoreApplication.translate("mainwindow", u"FilePath", None))
        self.textkeyhex_en.setText(QCoreApplication.translate("mainwindow", u"KEY__HEX", None))
        self.textpassword_en.setText(QCoreApplication.translate("mainwindow", u"Password", None))
        self.paste_password_en.setText(QCoreApplication.translate("mainwindow", u"Paste", None))
        self.encrypt.setText(QCoreApplication.translate("mainwindow", u"Encrypt", None))
        self.textoutput_en.setText(QCoreApplication.translate("mainwindow", u"Output", None))
        self.browsebutton_en_output.setText(QCoreApplication.translate("mainwindow", u"Browse", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_encrypt), QCoreApplication.translate("mainwindow", u"Encryption", None))
        self.textpassword_de.setText(QCoreApplication.translate("mainwindow", u"Password", None))
        self.textfilepath_de.setText(QCoreApplication.translate("mainwindow", u"FilePath", None))
        self.textkeyhex_de.setText(QCoreApplication.translate("mainwindow", u"KEY__HEX", None))
        self.browsebutton_de.setText(QCoreApplication.translate("mainwindow", u"Browse", None))
        self.paste_hex_de.setText(QCoreApplication.translate("mainwindow", u"Paste", None))
        self.paste_password_de.setText(QCoreApplication.translate("mainwindow", u"Paste", None))
        self.decrypt.setText(QCoreApplication.translate("mainwindow", u"Decrypt", None))
        self.textoutput_de.setText(QCoreApplication.translate("mainwindow", u"Output", None))
        self.browsebutton_de_output.setText(QCoreApplication.translate("mainwindow", u"Browse", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_decrypt), QCoreApplication.translate("mainwindow", u"Decryption", None))
    # retranslateUi

